# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: Y2ZlNjZkMDk4NWM4MWQ5MThjZTcwNmQwMjVjYzllMWQ1MTUwMGRkOTVmN2UwOWQ0NTFiMGFlNDU1ZmFkMGY1Y2I0N2I5ZjFlMDFmMjk0YmM2NjY3MjEzMDhhN2JjZDkxMTMzM2MxNWE4MGIwMmY5YWUwZGQ0MjBmMzA2MWI5Y2E=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
